// frontend/pages/support/index.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
    <!-- Header -->
    <div class="bg-white/5 backdrop-blur-lg border-b border-white/10">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-4">
            <NuxtLink to="/dashboard" class="text-gray-900/60 hover:text-gray-900 transition">
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
              </svg>
            </NuxtLink>
            <div>
              <h1 class="text-2xl font-bold text-gray-900">Centre d'Assistance</h1>
              <p class="text-gray-900/60 text-sm">Nous sommes là pour vous aider 24/7</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Quick Stats -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div class="bg-white/5 backdrop-blur-lg rounded-2xl p-6 border border-white/10">
          <div class="flex items-center gap-4">
            <div class="w-12 h-12 rounded-full bg-green-500/20 flex items-center justify-center">
              <svg class="w-6 h-6 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <div>
              <p class="text-gray-900/60 text-sm">Temps de réponse</p>
              <p class="text-gray-900 text-xl font-bold">~2 min</p>
            </div>
          </div>
        </div>
        <div class="bg-white/5 backdrop-blur-lg rounded-2xl p-6 border border-white/10">
          <div class="flex items-center gap-4">
            <div class="w-12 h-12 rounded-full bg-blue-500/20 flex items-center justify-center">
              <svg class="w-6 h-6 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <div>
              <p class="text-gray-900/60 text-sm">Disponibilité</p>
              <p class="text-gray-900 text-xl font-bold">24h/24 7j/7</p>
            </div>
          </div>
        </div>
        <div class="bg-white/5 backdrop-blur-lg rounded-2xl p-6 border border-white/10">
          <div class="flex items-center gap-4">
            <div class="w-12 h-12 rounded-full bg-purple-500/20 flex items-center justify-center">
              <svg class="w-6 h-6 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
              </svg>
            </div>
            <div>
              <p class="text-gray-900/60 text-sm">Satisfaction</p>
              <p class="text-gray-900 text-xl font-bold">98%</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Agent Selection -->
      <div class="mb-8" v-if="!selectedAgent && !activeConversation">
        <h2 class="text-xl font-semibold text-gray-900 mb-4">Comment souhaitez-vous être aidé ?</h2>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <!-- AI Agent Card -->
          <div 
            @click="selectAgent('ai')"
            class="group relative bg-gradient-to-br from-blue-500/20 to-purple-500/20 backdrop-blur-lg rounded-2xl p-8 border border-white/10 cursor-pointer hover:border-blue-400/50 transition-all duration-300 hover:scale-[1.02]"
          >
            <div class="absolute inset-0 bg-gradient-to-br from-blue-500/10 to-purple-500/10 rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity"></div>
            <div class="relative">
              <div class="w-20 h-20 rounded-2xl bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center mb-6 text-4xl">
                🤖
              </div>
              <h3 class="text-2xl font-bold text-gray-900 mb-2">Assistant IA</h3>
              <p class="text-gray-900/70 mb-4">Réponses instantanées 24/7 pour les questions courantes. Idéal pour les demandes simples.</p>
              <ul class="space-y-2">
                <li class="flex items-center gap-2 text-gray-900/80">
                  <svg class="w-5 h-5 text-green-400" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                  </svg>
                  Réponse instantanée
                </li>
                <li class="flex items-center gap-2 text-gray-900/80">
                  <svg class="w-5 h-5 text-green-400" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                  </svg>
                  Disponible 24h/24
                </li>
                <li class="flex items-center gap-2 text-gray-900/80">
                  <svg class="w-5 h-5 text-green-400" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                  </svg>
                  Escalade vers humain possible
                </li>
              </ul>
            </div>
          </div>

          <!-- Human Agent Card -->
          <div 
            @click="selectAgent('human')"
            class="group relative bg-gradient-to-br from-emerald-500/20 to-teal-500/20 backdrop-blur-lg rounded-2xl p-8 border border-white/10 cursor-pointer hover:border-emerald-400/50 transition-all duration-300 hover:scale-[1.02]"
          >
            <div class="absolute inset-0 bg-gradient-to-br from-emerald-500/10 to-teal-500/10 rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity"></div>
            <div class="relative">
              <div class="w-20 h-20 rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center mb-6 text-4xl">
                👤
              </div>
              <h3 class="text-2xl font-bold text-gray-900 mb-2">Conseiller Humain</h3>
              <p class="text-gray-900/70 mb-4">Pour les demandes complexes nécessitant une intervention ou une décision spécifique.</p>
              <ul class="space-y-2">
                <li class="flex items-center gap-2 text-gray-900/80">
                  <svg class="w-5 h-5 text-green-400" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                  </svg>
                  Analyse personnalisée
                </li>
                <li class="flex items-center gap-2 text-gray-900/80">
                  <svg class="w-5 h-5 text-green-400" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                  </svg>
                  Peut prendre des actions
                </li>
                <li class="flex items-center gap-2 text-gray-900/80">
                  <svg class="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd" />
                  </svg>
                  Attente : 2-5 min
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <!-- Start Conversation Form -->
      <div v-if="selectedAgent && !activeConversation" class="max-w-2xl mx-auto">
        <div class="bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-white/10">
          <div class="flex items-center gap-4 mb-6">
            <button @click="selectedAgent = null" class="text-gray-900/60 hover:text-gray-900">
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
              </svg>
            </button>
            <div class="flex items-center gap-3">
              <div class="w-12 h-12 rounded-xl flex items-center justify-center text-2xl" :class="selectedAgent === 'ai' ? 'bg-blue-500/20' : 'bg-emerald-500/20'">
                {{ selectedAgent === 'ai' ? '🤖' : '👤' }}
              </div>
              <div>
                <h3 class="text-gray-900 font-semibold">{{ selectedAgent === 'ai' ? 'Assistant IA' : 'Conseiller Humain' }}</h3>
                <p class="text-gray-900/60 text-sm">{{ selectedAgent === 'ai' ? 'Réponse instantanée' : 'Temps d\'attente: ~3 min' }}</p>
              </div>
            </div>
          </div>

          <form @submit.prevent="startConversation" class="space-y-6">
            <div>
              <label class="block text-gray-900/80 mb-2 text-sm font-medium">Sujet</label>
              <input 
                v-model="newConversation.subject" 
                type="text" 
                placeholder="Ex: Problème avec mon transfert"
                class="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-gray-900 placeholder-white/40 focus:outline-none focus:border-blue-500 transition"
                required
              />
            </div>

            <div>
              <label class="block text-gray-900/80 mb-2 text-sm font-medium">Catégorie</label>
              <select 
                v-model="newConversation.category"
                class="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-gray-900 focus:outline-none focus:border-blue-500 transition"
                required
              >
                <option value="" disabled class="text-gray-900">Sélectionner une catégorie</option>
                <option value="account" class="text-gray-900">💳 Compte & Cartes</option>
                <option value="transfer" class="text-gray-900">💸 Transferts & Virements</option>
                <option value="crypto" class="text-gray-900">₿ Cryptomonnaies</option>
                <option value="security" class="text-gray-900">🔐 Sécurité</option>
                <option value="fees" class="text-gray-900">📊 Frais & Facturation</option>
                <option value="other" class="text-gray-900">❓ Autre</option>
              </select>
            </div>

            <div>
              <label class="block text-gray-900/80 mb-2 text-sm font-medium">Décrivez votre demande</label>
              <textarea 
                v-model="newConversation.message"
                rows="4"
                placeholder="Expliquez votre problème ou question..."
                class="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-xl text-gray-900 placeholder-white/40 focus:outline-none focus:border-blue-500 transition resize-none"
                required
              ></textarea>
            </div>

            <button 
              type="submit"
              :disabled="loading"
              class="w-full py-4 bg-gradient-to-r from-blue-500 to-purple-600 text-gray-900 font-semibold rounded-xl hover:from-blue-600 hover:to-purple-700 transition-all duration-300 disabled:opacity-50"
            >
              <span v-if="loading" class="flex items-center justify-center gap-2">
                <svg class="animate-spin h-5 w-5" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" fill="none"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                Connexion en cours...
              </span>
              <span v-else>Démarrer la conversation</span>
            </button>
          </form>
        </div>
      </div>

      <!-- Existing Conversations -->
      <div v-if="!selectedAgent && !activeConversation && conversations.length > 0" class="mt-8">
        <h2 class="text-xl font-semibold text-gray-900 mb-4">Vos conversations</h2>
        <div class="space-y-4">
          <div 
            v-for="conv in conversations" 
            :key="conv.id"
            @click="openConversation(conv)"
            class="bg-white/5 backdrop-blur-lg rounded-xl p-4 border border-white/10 cursor-pointer hover:bg-white/10 transition"
          >
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-4">
                <div class="w-10 h-10 rounded-full flex items-center justify-center text-xl" :class="conv.agent_type === 'ai' ? 'bg-blue-500/20' : 'bg-emerald-500/20'">
                  {{ conv.agent_type === 'ai' ? '🤖' : '👤' }}
                </div>
                <div>
                  <h3 class="text-gray-900 font-medium">{{ conv.subject }}</h3>
                  <p class="text-gray-900/60 text-sm truncate max-w-md">{{ conv.last_message }}</p>
                </div>
              </div>
              <div class="text-right">
                <span :class="getStatusClass(conv.status)" class="px-2 py-1 rounded-full text-xs font-medium">
                  {{ getStatusLabel(conv.status) }}
                </span>
                <p class="text-gray-900/40 text-xs mt-1">{{ formatDate(conv.updated_at) }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'

definePageMeta({
  layout: 'default',
  middleware: 'auth'
})

const router = useRouter()

const selectedAgent = ref(null)
const activeConversation = ref(null)
const conversations = ref([])
const loading = ref(false)

const newConversation = ref({
  subject: '',
  category: '',
  message: ''
})

const selectAgent = (type) => {
  selectedAgent.value = type
}

const startConversation = async () => {
  loading.value = true
  
  try {
    // In production, this would call the API
    const response = await $fetch('/api/v1/support/conversations', {
      method: 'POST',
      body: {
        agent_type: selectedAgent.value,
        subject: newConversation.value.subject,
        category: newConversation.value.category,
        message: newConversation.value.message
      }
    })
    
    // Navigate to chat
    router.push(`/support/chat?id=${response.conversation.id}`)
  } catch (error) {
    console.error('Error starting conversation:', error)
    // For demo, navigate anyway
    router.push('/support/chat?id=demo-' + Date.now())
  } finally {
    loading.value = false
  }
}

const openConversation = (conv) => {
  router.push(`/support/chat?id=${conv.id}`)
}

const fetchConversations = async () => {
  try {
    const response = await $fetch('/api/v1/support/conversations')
    conversations.value = response.conversations || []
  } catch (error) {
    // Demo data
    conversations.value = [
      {
        id: '1',
        subject: 'Question sur mon transfert',
        agent_type: 'ai',
        status: 'resolved',
        last_message: 'Votre transfert a été traité avec succès.',
        updated_at: new Date().toISOString()
      }
    ]
  }
}

const getStatusClass = (status) => {
  const classes = {
    'open': 'bg-blue-500/20 text-blue-400',
    'pending': 'bg-yellow-500/20 text-yellow-400',
    'active': 'bg-green-500/20 text-green-400',
    'resolved': 'bg-emerald-500/20 text-emerald-400',
    'closed': 'bg-gray-500/20 text-gray-400',
    'escalated': 'bg-orange-500/20 text-orange-400'
  }
  return classes[status] || 'bg-gray-500/20 text-gray-400'
}

const getStatusLabel = (status) => {
  const labels = {
    'open': 'En attente',
    'pending': 'En cours',
    'active': 'Actif',
    'resolved': 'Résolu',
    'closed': 'Fermé',
    'escalated': 'Escaladé'
  }
  return labels[status] || status
}

const formatDate = (dateString) => {
  return new Date(dateString).toLocaleDateString('fr-FR', {
    day: 'numeric',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit'
  })
}

onMounted(() => {
  fetchConversations()
})
</script>

// admin-dashboard/src/app/dashboard/support/page.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import { getSupportTickets, getTicketMessages, sendTicketMessage, closeTicket, getSupportStats } from '@/lib/api';

interface Conversation {
    id: string;
    user_id: string;
    user_name: string;
    user_email: string;
    agent_type: 'ai' | 'human';
    subject: string;
    category: string;
    status: string;
    priority: string;
    last_message: string;
    unread_count: number;
    message_count: number;
    created_at: string;
    updated_at: string;
}

interface Message {
    id: string;
    sender_type: 'user' | 'agent' | 'system';
    sender_name: string;
    content: string;
    created_at: string;
}

interface Stats {
    total_conversations: number;
    open_conversations: number;
    resolved_today: number;
    pending_conversations: number;
    customer_satisfaction: number;
    active_agents: number;
}

export default function SupportPage() {
    const [conversations, setConversations] = useState<Conversation[]>([]);
    const [selectedConv, setSelectedConv] = useState<Conversation | null>(null);
    const [messages, setMessages] = useState<Message[]>([]);
    const [newMessage, setNewMessage] = useState('');
    const [filter, setFilter] = useState('all');
    const [stats, setStats] = useState<Stats | null>(null);
    const [sending, setSending] = useState(false);
    const [loading, setLoading] = useState(true);
    const messagesEndRef = useRef<HTMLDivElement>(null);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    const fetchConversations = async () => {
        try {
            const response = await getSupportTickets();
            // Map conversations from backend response
            const convs = response.data?.conversations || [];
            setConversations(convs.map((conv: any) => ({
                id: conv.id,
                user_id: conv.user_id,
                user_name: conv.user_name || 'Utilisateur',
                user_email: conv.user_email || '',
                agent_type: conv.agent_type || 'ai',
                subject: conv.subject,
                category: conv.category,
                status: conv.status,
                priority: conv.priority || 'medium',
                last_message: conv.last_message || conv.subject,
                unread_count: conv.unread_count || 0,
                message_count: conv.message_count || 1,
                created_at: conv.created_at,
                updated_at: conv.updated_at || conv.created_at
            })));
        } catch (error) {
            console.error('Failed to fetch conversations:', error);
            // Fallback demo data
            setConversations([
                {
                    id: '1',
                    user_id: 'u1',
                    user_name: 'Jean Dupont',
                    user_email: 'jean@example.com',
                    agent_type: 'human',
                    subject: 'Problème de transfert international',
                    category: 'transfer',
                    status: 'pending',
                    priority: 'high',
                    last_message: 'Mon transfert est bloqué depuis 2 jours...',
                    unread_count: 3,
                    message_count: 5,
                    created_at: new Date(Date.now() - 3600000).toISOString(),
                    updated_at: new Date(Date.now() - 600000).toISOString()
                }
            ]);
        } finally {
            setLoading(false);
        }
    };


    const fetchStats = async () => {
        try {
            const response = await getSupportStats();
            setStats(response.data);
        } catch (error) {
            // Fallback demo data
            setStats({
                total_conversations: 156,
                open_conversations: 23,
                resolved_today: 45,
                pending_conversations: 8,
                customer_satisfaction: 4.8,
                active_agents: 5
            });
        }
    };

    useEffect(() => {
        fetchConversations();
        fetchStats();
    }, []);

    useEffect(() => {
        scrollToBottom();
    }, [messages]);

    const selectConversation = (conv: Conversation) => {
        setSelectedConv(conv);
        // Load messages for this conversation
        setMessages([
            {
                id: 'm1',
                sender_type: 'user',
                sender_name: conv.user_name,
                content: `Bonjour, j'ai un problème avec mon compte concernant: ${conv.subject}`,
                created_at: new Date(Date.now() - 3600000).toISOString()
            },
            {
                id: 'm2',
                sender_type: 'agent',
                sender_name: 'Assistant IA',
                content: 'Bonjour ! Je comprends votre préoccupation. Pouvez-vous me donner plus de détails ?',
                created_at: new Date(Date.now() - 3500000).toISOString()
            },
            {
                id: 'm3',
                sender_type: 'user',
                sender_name: conv.user_name,
                content: conv.last_message,
                created_at: new Date(Date.now() - 600000).toISOString()
            }
        ]);
    };

    const sendMessage = async () => {
        if (!newMessage.trim() || !selectedConv) return;

        setSending(true);
        const content = newMessage;
        setNewMessage('');

        // Add message immediately
        setMessages(prev => [...prev, {
            id: 'msg-' + Date.now(),
            sender_type: 'agent',
            sender_name: 'Agent Support',
            content,
            created_at: new Date().toISOString()
        }]);

        // Simulate API call
        await new Promise(resolve => setTimeout(resolve, 500));
        setSending(false);
    };

    const handleAction = (action: string) => {
        if (!selectedConv) return;

        let systemMessage = '';
        switch (action) {
            case 'resolve':
                systemMessage = 'La conversation a été marquée comme résolue.';
                setSelectedConv({ ...selectedConv, status: 'resolved' });
                break;
            case 'escalate':
                systemMessage = 'La conversation a été escaladée au niveau supérieur.';
                break;
            case 'block-card':
                systemMessage = '🔒 La carte du client a été bloquée avec succès.';
                break;
            case 'refund':
                systemMessage = '💰 Un remboursement a été initié pour le client.';
                break;
        }

        setMessages(prev => [...prev, {
            id: 'sys-' + Date.now(),
            sender_type: 'system',
            sender_name: 'Système',
            content: systemMessage,
            created_at: new Date().toISOString()
        }]);
    };

    const getPriorityColor = (priority: string) => {
        switch (priority) {
            case 'urgent': return 'bg-red-500';
            case 'high': return 'bg-orange-500';
            case 'medium': return 'bg-yellow-500';
            default: return 'bg-green-500';
        }
    };

    const getStatusBadge = (status: string) => {
        switch (status) {
            case 'pending': return 'bg-yellow-500/20 text-yellow-400';
            case 'active': return 'bg-green-500/20 text-green-400';
            case 'escalated': return 'bg-orange-500/20 text-orange-400';
            case 'resolved': return 'bg-blue-500/20 text-blue-400';
            default: return 'bg-gray-500/20 text-gray-400';
        }
    };

    const filteredConversations = conversations.filter(c => {
        if (filter === 'all') return true;
        if (filter === 'pending') return c.status === 'pending' || c.status === 'escalated';
        if (filter === 'active') return c.status === 'active';
        if (filter === 'urgent') return c.priority === 'urgent' || c.priority === 'high';
        return true;
    });

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold text-white">Centre de Support</h1>
                    <p className="text-gray-400">Gérez les conversations et assistez les clients</p>
                </div>
                <div className="flex items-center gap-4">
                    <div className="flex items-center gap-2">
                        <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
                        <span className="text-green-400 text-sm">5 agents en ligne</span>
                    </div>
                </div>
            </div>

            {/* Stats */}
            {stats && (
                <div className="grid grid-cols-1 md:grid-cols-6 gap-4">
                    <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
                        <p className="text-gray-400 text-sm">En attente</p>
                        <p className="text-2xl font-bold text-yellow-400">{stats.pending_conversations}</p>
                    </div>
                    <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
                        <p className="text-gray-400 text-sm">Ouvertes</p>
                        <p className="text-2xl font-bold text-blue-400">{stats.open_conversations}</p>
                    </div>
                    <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
                        <p className="text-gray-400 text-sm">Résolues (24h)</p>
                        <p className="text-2xl font-bold text-green-400">{stats.resolved_today}</p>
                    </div>
                    <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
                        <p className="text-gray-400 text-sm">Total</p>
                        <p className="text-2xl font-bold text-white">{stats.total_conversations}</p>
                    </div>
                    <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
                        <p className="text-gray-400 text-sm">Satisfaction</p>
                        <p className="text-2xl font-bold text-purple-400">{stats.customer_satisfaction}/5 ⭐</p>
                    </div>
                    <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700">
                        <p className="text-gray-400 text-sm">Agents actifs</p>
                        <p className="text-2xl font-bold text-emerald-400">{stats.active_agents}</p>
                    </div>
                </div>
            )}

            {/* Main Content */}
            <div className="flex gap-6 h-[calc(100vh-300px)] min-h-[500px]">
                {/* Conversations List */}
                <div className="w-1/3 bg-slate-800/50 rounded-xl border border-slate-700 flex flex-col">
                    {/* Filters */}
                    <div className="p-4 border-b border-slate-700">
                        <div className="flex gap-2 flex-wrap">
                            {['all', 'pending', 'active', 'urgent'].map(f => (
                                <button
                                    key={f}
                                    onClick={() => setFilter(f)}
                                    className={`px-3 py-1 rounded-full text-sm transition ${filter === f
                                        ? 'bg-blue-500 text-white'
                                        : 'bg-slate-700 text-gray-300 hover:bg-slate-600'
                                        }`}
                                >
                                    {f === 'all' && 'Tous'}
                                    {f === 'pending' && 'En attente'}
                                    {f === 'active' && 'Actifs'}
                                    {f === 'urgent' && '🔥 Urgents'}
                                </button>
                            ))}
                        </div>
                    </div>

                    {/* List */}
                    <div className="flex-1 overflow-y-auto">
                        {filteredConversations.map(conv => (
                            <div
                                key={conv.id}
                                onClick={() => selectConversation(conv)}
                                className={`p-4 border-b border-slate-700 cursor-pointer transition hover:bg-slate-700/50 ${selectedConv?.id === conv.id ? 'bg-slate-700/50 border-l-2 border-l-blue-500' : ''
                                    }`}
                            >
                                <div className="flex items-start gap-3">
                                    <div className={`w-2 h-2 rounded-full mt-2 ${getPriorityColor(conv.priority)}`}></div>
                                    <div className="flex-1 min-w-0">
                                        <div className="flex items-center justify-between">
                                            <h3 className="font-medium text-white truncate">{conv.user_name}</h3>
                                            {conv.unread_count > 0 && (
                                                <span className="bg-blue-500 text-white text-xs px-2 py-0.5 rounded-full">
                                                    {conv.unread_count}
                                                </span>
                                            )}
                                        </div>
                                        <p className="text-sm text-gray-300 truncate">{conv.subject}</p>
                                        <p className="text-xs text-gray-500 truncate mt-1">{conv.last_message}</p>
                                        <div className="flex items-center gap-2 mt-2">
                                            <span className={`px-2 py-0.5 rounded-full text-xs ${getStatusBadge(conv.status)}`}>
                                                {conv.status}
                                            </span>
                                            <span className="text-xs text-gray-500">
                                                {conv.agent_type === 'ai' ? '🤖' : '👤'}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Chat Area */}
                <div className="flex-1 bg-slate-800/50 rounded-xl border border-slate-700 flex flex-col">
                    {selectedConv ? (
                        <>
                            {/* Chat Header */}
                            <div className="p-4 border-b border-slate-700 flex items-center justify-between">
                                <div>
                                    <h2 className="font-semibold text-white">{selectedConv.user_name}</h2>
                                    <p className="text-sm text-gray-400">{selectedConv.user_email} • {selectedConv.subject}</p>
                                </div>
                                <div className="flex items-center gap-2">
                                    <span className={`px-3 py-1 rounded-full text-xs ${getStatusBadge(selectedConv.status)}`}>
                                        {selectedConv.status}
                                    </span>
                                </div>
                            </div>

                            {/* Messages */}
                            <div className="flex-1 overflow-y-auto p-4 space-y-4">
                                {messages.map(msg => (
                                    <div
                                        key={msg.id}
                                        className={`flex ${msg.sender_type === 'agent' ? 'justify-end' : msg.sender_type === 'system' ? 'justify-center' : 'justify-start'}`}
                                    >
                                        {msg.sender_type === 'system' ? (
                                            <div className="bg-slate-700 text-gray-300 text-sm px-4 py-2 rounded-full">
                                                {msg.content}
                                            </div>
                                        ) : (
                                            <div className={`max-w-[70%] ${msg.sender_type === 'agent' ? 'order-2' : ''}`}>
                                                <div className={`rounded-xl p-3 ${msg.sender_type === 'agent'
                                                    ? 'bg-blue-500 text-white rounded-tr-none'
                                                    : 'bg-slate-700 text-white rounded-tl-none'
                                                    }`}>
                                                    <p className="text-sm font-medium mb-1">{msg.sender_name}</p>
                                                    <p className="whitespace-pre-wrap">{msg.content}</p>
                                                </div>
                                                <p className={`text-xs text-gray-500 mt-1 ${msg.sender_type === 'agent' ? 'text-right' : ''}`}>
                                                    {new Date(msg.created_at).toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' })}
                                                </p>
                                            </div>
                                        )}
                                    </div>
                                ))}
                                <div ref={messagesEndRef} />
                            </div>

                            {/* Actions */}
                            <div className="p-3 border-t border-slate-700 flex gap-2 flex-wrap">
                                <button onClick={() => handleAction('resolve')} className="px-3 py-1.5 bg-green-500/20 text-green-400 rounded-lg text-sm hover:bg-green-500/30">
                                    ✓ Résoudre
                                </button>
                                <button onClick={() => handleAction('escalate')} className="px-3 py-1.5 bg-orange-500/20 text-orange-400 rounded-lg text-sm hover:bg-orange-500/30">
                                    ⬆ Escalader
                                </button>
                                <button onClick={() => handleAction('block-card')} className="px-3 py-1.5 bg-red-500/20 text-red-400 rounded-lg text-sm hover:bg-red-500/30">
                                    🔒 Bloquer carte
                                </button>
                                <button onClick={() => handleAction('refund')} className="px-3 py-1.5 bg-purple-500/20 text-purple-400 rounded-lg text-sm hover:bg-purple-500/30">
                                    💰 Rembourser
                                </button>
                            </div>

                            {/* Input */}
                            <div className="p-4 border-t border-slate-700">
                                <div className="flex gap-3">
                                    <input
                                        type="text"
                                        value={newMessage}
                                        onChange={(e) => setNewMessage(e.target.value)}
                                        onKeyPress={(e) => e.key === 'Enter' && sendMessage()}
                                        placeholder="Tapez votre réponse..."
                                        className="flex-1 bg-slate-700 text-white rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-blue-500"
                                        disabled={sending}
                                    />
                                    <button
                                        onClick={sendMessage}
                                        disabled={!newMessage.trim() || sending}
                                        className="px-6 py-3 bg-blue-500 text-white rounded-xl hover:bg-blue-600 transition disabled:opacity-50"
                                    >
                                        Envoyer
                                    </button>
                                </div>
                            </div>
                        </>
                    ) : (
                        <div className="flex-1 flex items-center justify-center text-gray-500">
                            <div className="text-center">
                                <p className="text-4xl mb-4">💬</p>
                                <p>Sélectionnez une conversation</p>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
