// admin-dashboard/src/app/dashboard/kyc/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { getUsers, approveKYC, rejectKYC } from '@/lib/api';

interface User {
    id: string;
    email: string;
    first_name: string;
    last_name: string;
    phone: string;
    kyc_level: number;
    kyc_status: string;
    is_active: boolean;
    created_at: string;
}

export default function KYCPage() {
    const [users, setUsers] = useState<User[]>([]);
    const [allUsers, setAllUsers] = useState<User[]>([]);
    const [loading, setLoading] = useState(true);
    const [actionLoading, setActionLoading] = useState<string | null>(null);
    const [filter, setFilter] = useState('pending');

    const fetchUsers = async () => {
        try {
            setLoading(true);
            const response = await getUsers();
            const userList = response.data?.users || [];
            setAllUsers(userList);
        } catch (error) {
            console.error('Failed to fetch users:', error);
            setAllUsers([]);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchUsers();
    }, []);

    useEffect(() => {
        // Filter users based on selected filter
        if (filter === 'all') {
            setUsers(allUsers);
        } else {
            setUsers(allUsers.filter((u: User) => u.kyc_status === filter));
        }
    }, [filter, allUsers]);

    const handleApprove = async (userId: string) => {
        if (!confirm('Approuver cette demande KYC ?')) return;

        setActionLoading(userId);
        try {
            await approveKYC(userId, 'verified');
            await fetchUsers();
            alert('KYC approuvé avec succès');
        } catch (error) {
            console.error('Failed to approve KYC:', error);
            alert('Erreur lors de l\'approbation');
        } finally {
            setActionLoading(null);
        }
    };

    const handleReject = async (userId: string) => {
        const reason = prompt('Raison du rejet:');
        if (!reason) return;

        setActionLoading(userId);
        try {
            await rejectKYC(userId, reason);
            await fetchUsers();
            alert('KYC rejeté');
        } catch (error) {
            console.error('Failed to reject KYC:', error);
            alert('Erreur lors du rejet');
        } finally {
            setActionLoading(null);
        }
    };

    const getStatusBadge = (status: string) => {
        switch (status) {
            case 'pending':
                return 'bg-yellow-100 text-yellow-800';
            case 'verified':
                return 'bg-green-100 text-green-800';
            case 'rejected':
                return 'bg-red-100 text-red-800';
            case 'none':
                return 'bg-gray-100 text-gray-800';
            default:
                return 'bg-gray-100 text-gray-800';
        }
    };

    const getStatusLabel = (status: string) => {
        switch (status) {
            case 'pending': return 'En attente';
            case 'verified': return 'Vérifié';
            case 'rejected': return 'Rejeté';
            case 'none': return 'Non soumis';
            default: return status || 'Inconnu';
        }
    };

    const formatDate = (dateString: string) => {
        if (!dateString) return '-';
        try {
            return new Date(dateString).toLocaleDateString('fr-FR', {
                day: '2-digit',
                month: '2-digit',
                year: 'numeric'
            });
        } catch {
            return '-';
        }
    };

    const pendingCount = allUsers.filter(u => u.kyc_status === 'pending').length;
    const verifiedCount = allUsers.filter(u => u.kyc_status === 'verified').length;
    const rejectedCount = allUsers.filter(u => u.kyc_status === 'rejected').length;

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex items-center justify-between flex-wrap gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-slate-900">Vérification KYC</h1>
                    <p className="text-gray-500">Gérez les demandes de vérification d'identité</p>
                </div>
                <button
                    onClick={fetchUsers}
                    className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700"
                >
                    ↻ Actualiser
                </button>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div className="bg-white rounded-xl p-4 border border-gray-200 shadow-sm">
                    <p className="text-gray-500 text-sm">Total utilisateurs</p>
                    <p className="text-2xl font-bold text-slate-900">{allUsers.length}</p>
                </div>
                <div className="bg-white rounded-xl p-4 border border-gray-200 shadow-sm border-l-4 border-l-yellow-500">
                    <p className="text-gray-500 text-sm">En attente</p>
                    <p className="text-2xl font-bold text-yellow-600">{pendingCount}</p>
                </div>
                <div className="bg-white rounded-xl p-4 border border-gray-200 shadow-sm border-l-4 border-l-green-500">
                    <p className="text-gray-500 text-sm">Vérifiés</p>
                    <p className="text-2xl font-bold text-green-600">{verifiedCount}</p>
                </div>
                <div className="bg-white rounded-xl p-4 border border-gray-200 shadow-sm border-l-4 border-l-red-500">
                    <p className="text-gray-500 text-sm">Rejetés</p>
                    <p className="text-2xl font-bold text-red-600">{rejectedCount}</p>
                </div>
            </div>

            {/* Filters */}
            <div className="flex gap-2 flex-wrap">
                {[
                    { key: 'pending', label: `🕐 En attente (${pendingCount})` },
                    { key: 'verified', label: `✅ Vérifiés (${verifiedCount})` },
                    { key: 'rejected', label: `❌ Rejetés (${rejectedCount})` },
                    { key: 'all', label: 'Tous' }
                ].map(f => (
                    <button
                        key={f.key}
                        onClick={() => setFilter(f.key)}
                        className={`px-4 py-2 rounded-lg text-sm font-medium transition ${filter === f.key
                                ? 'bg-primary-600 text-white'
                                : 'bg-white text-gray-600 border border-gray-200 hover:bg-gray-50'
                            }`}
                    >
                        {f.label}
                    </button>
                ))}
            </div>

            {/* Content */}
            {loading ? (
                <div className="flex items-center justify-center h-64">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
                </div>
            ) : users.length === 0 ? (
                <div className="bg-white rounded-xl p-12 text-center border border-gray-200">
                    <p className="text-4xl mb-4">📋</p>
                    <p className="text-gray-500">Aucune demande {filter === 'pending' ? 'en attente' : ''}</p>
                </div>
            ) : (
                <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
                    <table className="w-full">
                        <thead className="bg-gray-50 border-b border-gray-200">
                            <tr>
                                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Utilisateur</th>
                                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Contact</th>
                                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Niveau</th>
                                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Statut</th>
                                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Inscription</th>
                                <th className="text-right px-6 py-3 text-xs font-medium text-gray-500 uppercase">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100">
                            {users.map((user) => (
                                <tr key={user.id} className="hover:bg-gray-50">
                                    <td className="px-6 py-4">
                                        <div className="flex items-center gap-3">
                                            <div className={`w-10 h-10 rounded-full flex items-center justify-center font-medium ${user.kyc_status === 'pending' ? 'bg-yellow-100 text-yellow-600' :
                                                    user.kyc_status === 'verified' ? 'bg-green-100 text-green-600' :
                                                        'bg-gray-100 text-gray-600'
                                                }`}>
                                                {(user.first_name?.[0] || '')}{(user.last_name?.[0] || '')}
                                            </div>
                                            <div>
                                                <p className="font-medium text-slate-900">
                                                    {user.first_name} {user.last_name}
                                                </p>
                                                <p className="text-sm text-gray-500">{user.id?.slice(0, 8)}...</p>
                                            </div>
                                        </div>
                                    </td>
                                    <td className="px-6 py-4">
                                        <p className="text-sm text-slate-900">{user.email}</p>
                                        <p className="text-sm text-gray-500">{user.phone || '-'}</p>
                                    </td>
                                    <td className="px-6 py-4">
                                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                                            Niveau {user.kyc_level || 0}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4">
                                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusBadge(user.kyc_status)}`}>
                                            {getStatusLabel(user.kyc_status)}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4 text-sm text-gray-500">
                                        {formatDate(user.created_at)}
                                    </td>
                                    <td className="px-6 py-4 text-right">
                                        {user.kyc_status === 'pending' && (
                                            <div className="flex gap-2 justify-end">
                                                <button
                                                    onClick={() => handleApprove(user.id)}
                                                    disabled={actionLoading === user.id}
                                                    className="px-3 py-1.5 bg-green-600 text-white rounded-lg text-sm hover:bg-green-700 disabled:opacity-50"
                                                >
                                                    {actionLoading === user.id ? '...' : '✓ Approuver'}
                                                </button>
                                                <button
                                                    onClick={() => handleReject(user.id)}
                                                    disabled={actionLoading === user.id}
                                                    className="px-3 py-1.5 bg-red-600 text-white rounded-lg text-sm hover:bg-red-700 disabled:opacity-50"
                                                >
                                                    ✗ Rejeter
                                                </button>
                                            </div>
                                        )}
                                        {user.kyc_status === 'verified' && (
                                            <span className="text-green-600 text-sm">✓ Approuvé</span>
                                        )}
                                        {user.kyc_status === 'rejected' && (
                                            <button
                                                onClick={() => handleApprove(user.id)}
                                                disabled={actionLoading === user.id}
                                                className="px-3 py-1.5 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-700 disabled:opacity-50"
                                            >
                                                Réexaminer
                                            </button>
                                        )}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
}

// frontend/pages/admin/kyc.vue
<template>
  <NuxtLayout name="admin">
    <div class="p-8">
      <div class="mb-8">
        <h1 class="text-3xl font-bold text-white mb-2">Vérification KYC</h1>
        <p class="text-slate-400">Queue de validation des documents d'identité.</p>
      </div>

       <!-- Tabs -->
      <div class="flex space-x-4 mb-6 border-b border-slate-700">
        <button 
          v-for="status in ['pending', 'approved', 'rejected', 'all']"
          :key="status"
          @click="activeStatus = status; offset = 0; fetchRequests()"
          class="pb-2 px-4 text-sm font-medium transition-colors relative capitalize"
          :class="activeStatus === status ? 'text-indigo-400 border-b-2 border-indigo-400' : 'text-slate-400 hover:text-white'"
        >
          {{ status === 'pending' ? 'En attente' : status === 'approved' ? 'Validés' : status === 'rejected' ? 'Rejetés' : 'Tous' }}
        </button>
      </div>

      <!-- Content -->
      <div v-if="loading" class="flex justify-center py-12">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-500"></div>
      </div>

      <div v-else class="bg-slate-800/50 backdrop-blur-xl rounded-2xl border border-slate-700/50 overflow-hidden">
        <div class="overflow-x-auto">
          <table class="w-full text-left">
            <thead class="bg-slate-900/50 text-slate-400 text-xs uppercase font-medium">
              <tr>
                <th class="px-6 py-4">Utilisateur</th>
                <th class="px-6 py-4">Type Document</th>
                <th class="px-6 py-4">Fichier</th>
                <th class="px-6 py-4">Date de soumission</th>
                <th class="px-6 py-4">Statut</th>
                <th class="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-700/50">
              <tr v-for="req in requests" :key="req.document.id" class="hover:bg-slate-700/20 transition-colors">
                <td class="px-6 py-4">
                  <div class="font-medium text-white">{{ req.user_name }}</div>
                  <div class="text-xs text-slate-400">{{ req.user_email }}</div>
                </td>
                <td class="px-6 py-4">
                  <div class="capitalize text-slate-300">{{ req.document.type }}</div>
                  <div v-if="req.document.identity_sub_type" class="text-xs text-slate-500 capitalize">
                    {{ req.document.identity_sub_type }}
                  </div>
                </td>
                <td class="px-6 py-4 text-sm text-indigo-400">
                  <a :href="req.document.file_path" target="_blank" class="hover:underline flex items-center gap-1">
                    📄 {{ req.document.file_name }}
                  </a>
                </td>
                <td class="px-6 py-4 text-xs text-slate-400">
                  {{ formatDate(req.document.uploaded_at) }}
                </td>
                <td class="px-6 py-4">
                   <span class="px-2 py-1 rounded-full text-xs font-medium" 
                    :class="{
                      'bg-emerald-500/10 text-emerald-400': req.document.status === 'approved',
                      'bg-red-500/10 text-red-400': req.document.status === 'rejected',
                      'bg-amber-500/10 text-amber-400': req.document.status === 'pending'
                    }">
                    {{ req.document.status }}
                  </span>
                </td>
                <td class="px-6 py-4 text-right">
                  <button 
                    v-if="req.document.status === 'pending'"
                    @click="openReviewModal(req)" 
                    class="bg-indigo-500 hover:bg-indigo-600 text-white px-3 py-1 rounded-lg text-sm font-medium transition-colors"
                  >
                    Examiner
                  </button>
                  <span v-else class="text-xs text-slate-500">
                     {{ req.document.status === 'approved' ? 'Validé' : 'Rejeté' }}
                     <span v-if="req.document.reviewed_at">le {{ formatDate(req.document.reviewed_at) }}</span>
                  </span>
                </td>
              </tr>
              <tr v-if="requests.length === 0">
                <td colspan="6" class="px-6 py-8 text-center text-slate-400">
                  Aucun document à vérifier.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <!-- Pagination -->
        <div class="px-6 py-4 border-t border-slate-700/50 flex justify-between items-center">
          <button @click="prevPage" :disabled="offset === 0" class="text-slate-400 hover:text-white disabled:opacity-50">
            ← Précédent
          </button>
           <span class="text-slate-500 text-sm">Total: {{ total }}</span>
          <button @click="nextPage" :disabled="offset + limit >= total" class="text-slate-400 hover:text-white disabled:opacity-50">
            Suivant →
          </button>
        </div>
      </div>
    </div>

    <!-- Review Modal -->
    <div v-if="showModal" class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/90 backdrop-blur-sm">
      <div class="bg-slate-800 rounded-2xl border border-slate-700 w-full max-w-4xl shadow-xl max-h-[90vh] overflow-y-auto" @click.stop>
        <div class="p-6 border-b border-slate-700 flex justify-between items-center sticky top-0 bg-slate-800 z-10">
          <div>
            <h2 class="text-xl font-bold text-white">Examen du document</h2>
            <p class="text-sm text-slate-400">{{ selectedReq?.user_name }} - {{ selectedReq?.document.type }}</p>
          </div>
          <button @click="closeModal" class="text-slate-400 hover:text-white">✕</button>
        </div>
        
        <div class="p-6 grid grid-cols-1 md:grid-cols-2 gap-8">
           <!-- Document Preview -->
           <div class="bg-slate-900 rounded-xl p-2 border border-slate-700 flex items-center justify-center min-h-[400px]">
             <img 
               v-if="isImage(selectedReq?.document.mime_type)" 
               :src="selectedReq?.document.file_path" 
               class="max-w-full max-h-[500px] object-contain"
             />
             <iframe 
               v-else-if="selectedReq?.document.mime_type === 'application/pdf'" 
               :src="selectedReq?.document.file_path" 
               class="w-full h-[500px]"
             ></iframe>
             <div v-else class="text-center p-8">
               <p class="text-slate-400 mb-4">Aperçu non disponible pour ce format</p>
               <a :href="selectedReq?.document.file_path" target="_blank" class="text-indigo-400 underline">Télécharger le fichier</a>
             </div>
           </div>

           <!-- Actions -->
           <div class="space-y-6">
             <div class="bg-slate-700/30 rounded-xl p-4 border border-slate-700">
               <h3 class="font-medium text-white mb-4">Détails détectés</h3>
               <dl class="space-y-2 text-sm">
                 <div class="flex justify-between">
                   <dt class="text-slate-400">Numéro document (OCR)</dt>
                   <dd class="text-white font-mono">{{ selectedReq?.document.document_number || 'Non détecté' }}</dd>
                 </div>
                 <div class="flex justify-between">
                   <dt class="text-slate-400">Date expiration</dt>
                   <dd class="text-white font-mono">{{ selectedReq?.document.expiry_date || 'Non détectée' }}</dd>
                 </div>
               </dl>
             </div>

             <div v-if="reviewAction === 'reject'" class="space-y-2">
               <label class="text-sm font-medium text-slate-300">Raison du rejet</label>
               <textarea 
                 v-model="rejectionReason"
                 class="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-red-500 h-24"
                 placeholder="Expliquez pourquoi le document est rejeté..."
               ></textarea>
             </div>

             <div class="flex flex-col gap-3">
               <div v-if="reviewAction !== 'reject'" class="grid grid-cols-2 gap-3">
                 <button 
                   @click="reviewAction = 'reject'" 
                   class="px-4 py-3 rounded-xl border border-red-500/30 text-red-400 hover:bg-red-500/10 transition-colors"
                 >
                   Refuser
                 </button>
                 <button 
                   @click="submitReview('approved')" 
                   :disabled="submitting"
                   class="px-4 py-3 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-white font-medium transition-colors"
                 >
                   <span v-if="submitting">Traitement...</span>
                   <span v-else>✅ Valider le document</span>
                 </button>
               </div>

               <div v-else class="grid grid-cols-2 gap-3">
                 <button 
                   @click="reviewAction = null" 
                   class="px-4 py-3 rounded-xl border border-slate-600 text-slate-300 hover:bg-slate-700 transition-colors"
                 >
                   Annuler
                 </button>
                 <button 
                   @click="submitReview('rejected')" 
                   :disabled="submitting || !rejectionReason"
                   class="px-4 py-3 rounded-xl bg-red-500 hover:bg-red-600 text-white font-medium transition-colors"
                 >
                   <span v-if="submitting">Traitement...</span>
                   <span v-else>🚫 Confirmer le rejet</span>
                 </button>
               </div>
             </div>
           </div>
        </div>
      </div>
    </div>
  </NuxtLayout>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useApi } from '@/composables/useApi'

const { adminKYCAPI } = useApi()

const loading = ref(true)
const requests = ref([])
const total = ref(0)
const limit = ref(20)
const offset = ref(0)
const activeStatus = ref('pending')

const showModal = ref(false)
const selectedReq = ref(null)
const reviewAction = ref(null)
const rejectionReason = ref('')
const submitting = ref(false)

const fetchRequests = async () => {
  loading.value = true
  try {
    const response = await adminKYCAPI.getRequests(activeStatus.value, limit.value, offset.value)
    requests.value = response.data?.requests || []
    total.value = response.data?.total || 0
  } catch (error) {
    console.error("Failed to fetch KYC request", error)
  } finally {
    loading.value = false
  }
}

const nextPage = () => {
  if (offset.value + limit.value < total.value) {
    offset.value += limit.value
    fetchRequests()
  }
}

const prevPage = () => {
  if (offset.value >= limit.value) {
    offset.value -= limit.value
    fetchRequests()
  }
}

const openReviewModal = (req) => {
  selectedReq.value = req
  reviewAction.value = null
  rejectionReason.value = ''
  showModal.value = true
}

const closeModal = () => {
  showModal.value = false
  selectedReq.value = null
}

const submitReview = async (status) => {
  if (!selectedReq.value) return
  
  submitting.value = true
  try {
    await adminKYCAPI.reviewRequest(selectedReq.value.document.id, status, rejectionReason.value)
    
    // Remove from list if viewing pending, or update status
    if (activeStatus.value === 'pending') {
      requests.value = requests.value.filter(r => r.document.id !== selectedReq.value.document.id)
      total.value--
    } else {
      fetchRequests()
    }
    
    closeModal()
  } catch (error) {
    console.error("Failed to review document", error)
    alert("Erreur: " + (error.response?.data?.error || error.message))
  } finally {
    submitting.value = false
  }
}

const isImage = (mimeType) => {
  return mimeType && mimeType.startsWith('image/')
}

const formatDate = (dateString) => {
  if (!dateString) return '-'
  return new Date(dateString).toLocaleString('fr-FR')
}

onMounted(() => {
  fetchRequests()
})
</script>
