// admin-dashboard/src/app/dashboard/users/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { getUsers, blockUser, unblockUser } from '@/lib/api';
import { format } from 'date-fns';

interface User {
    id: string;
    email: string;
    first_name: string;
    last_name: string;
    phone: string;
    is_active: boolean;
    kyc_level: number | string;
    created_at: string;
}

export default function UsersPage() {
    const [users, setUsers] = useState<User[]>([]);
    const [loading, setLoading] = useState(true);
    const [actionLoading, setActionLoading] = useState<string | null>(null);

    const fetchUsers = async () => {
        try {
            const response = await getUsers();
            setUsers(response.data.users || []);
        } catch (error) {
            console.error('Failed to fetch users:', error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchUsers();
    }, []);

    const handleBlock = async (userId: string) => {
        const reason = prompt('Raison du blocage:');
        if (!reason) return;

        setActionLoading(userId);
        try {
            await blockUser(userId, reason);
            await fetchUsers();
            alert('Utilisateur bloqué');
        } catch (error) {
            alert('Erreur lors du blocage');
        } finally {
            setActionLoading(null);
        }
    };

    const handleUnblock = async (userId: string) => {
        setActionLoading(userId);
        try {
            await unblockUser(userId);
            await fetchUsers();
            alert('Utilisateur débloqué');
        } catch (error) {
            alert('Erreur lors du déblocage');
        } finally {
            setActionLoading(null);
        }
    };

    if (loading) {
        return (
            <div className="flex items-center justify-center h-64">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
            </div>
        );
    }

    return (
        <div>
            <div className="mb-8 flex justify-between items-center">
                <div>
                    <h1 className="text-2xl font-bold text-slate-900">Utilisateurs</h1>
                    <p className="text-slate-500 mt-1">{users.length} utilisateurs enregistrés</p>
                </div>
            </div>

            <div className="table-container">
                <table className="w-full">
                    <thead className="bg-gray-50 border-b">
                        <tr>
                            <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">Utilisateur</th>
                            <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">Email</th>
                            <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">Téléphone</th>
                            <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">KYC</th>
                            <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">Status</th>
                            <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">Inscrit le</th>
                            <th className="text-right px-6 py-4 text-sm font-medium text-slate-600">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                        {users.map((user) => (
                            <tr key={user.id} className="hover:bg-gray-50">
                                <td className="px-6 py-4">
                                    <div className="flex items-center gap-3">
                                        <div className="w-10 h-10 rounded-full bg-primary-100 flex items-center justify-center text-primary-600 font-medium">
                                            {user.first_name?.[0]}{user.last_name?.[0]}
                                        </div>
                                        <div>
                                            <p className="font-medium text-slate-900">{user.first_name} {user.last_name}</p>
                                            <p className="text-sm text-slate-500 truncate max-w-[200px]">{user.id}</p>
                                        </div>
                                    </div>
                                </td>
                                <td className="px-6 py-4 text-slate-700">{user.email}</td>
                                <td className="px-6 py-4 text-slate-700">{user.phone || '-'}</td>
                                <td className="px-6 py-4">
                                    <span className={`badge ${getKYCBadge(user.kyc_level)}`}>
                                        Niveau {user.kyc_level}
                                    </span>
                                </td>
                                <td className="px-6 py-4">
                                    <span className={`badge ${user.is_active ? 'badge-success' : 'badge-danger'}`}>
                                        {user.is_active ? 'Actif' : 'Bloqué'}
                                    </span>
                                </td>
                                <td className="px-6 py-4 text-slate-500 text-sm">
                                    {user.created_at ? format(new Date(user.created_at), 'dd/MM/yyyy') : '-'}
                                </td>
                                <td className="px-6 py-4 text-right">
                                    {user.is_active ? (
                                        <button
                                            onClick={() => handleBlock(user.id)}
                                            disabled={actionLoading === user.id}
                                            className="btn-danger text-sm px-3 py-1"
                                        >
                                            {actionLoading === user.id ? '...' : 'Bloquer'}
                                        </button>
                                    ) : (
                                        <button
                                            onClick={() => handleUnblock(user.id)}
                                            disabled={actionLoading === user.id}
                                            className="btn-primary text-sm px-3 py-1"
                                        >
                                            {actionLoading === user.id ? '...' : 'Débloquer'}
                                        </button>
                                    )}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
                {users.length === 0 && (
                    <div className="text-center py-12 text-slate-500">
                        Aucun utilisateur trouvé
                    </div>
                )}
            </div>
        </div>
    );
}

function getKYCBadge(level: number | string): string {
    switch (String(level)) {
        case '3':
        case 'verified':
            return 'badge-success';
        case '2':
            return 'badge-info';
        case 'pending':
            return 'badge-warning';
        default:
            return 'badge-warning';
    }
}

// frontend/pages/admin/users.vue
<template>
  <NuxtLayout name="admin">
    <div class="p-8">
      <div class="mb-8">
        <h1 class="text-3xl font-bold text-white mb-2">Utilisateurs</h1>
        <p class="text-slate-400">Gestion des utilisateurs et de leurs permissions.</p>
      </div>

      <!-- Content -->
      <div v-if="loading" class="flex justify-center py-12">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-500"></div>
      </div>

      <div v-else class="bg-slate-800/50 backdrop-blur-xl rounded-2xl border border-slate-700/50 overflow-hidden">
        <div class="overflow-x-auto">
          <table class="w-full text-left">
            <thead class="bg-slate-900/50 text-slate-400 text-xs uppercase font-medium">
              <tr>
                <th class="px-6 py-4">Utilisateur</th>
                <th class="px-6 py-4">Contact</th>
                <th class="px-6 py-4">Rôle</th>
                <th class="px-6 py-4">Statut</th>
                <th class="px-6 py-4">KYC</th>
                <th class="px-6 py-4">Dernière connexion</th>
                <th class="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-700/50">
              <tr v-for="user in users" :key="user.id" class="hover:bg-slate-700/20 transition-colors">
                <td class="px-6 py-4">
                  <div class="flex items-center gap-3">
                    <div class="w-8 h-8 rounded-full bg-indigo-500/20 flex items-center justify-center text-indigo-400 font-bold text-sm">
                      {{ user.name.charAt(0) }}
                    </div>
                    <div>
                      <div class="font-medium text-white">{{ user.name }}</div>
                      <div class="text-xs text-slate-500">ID: {{ user.id.substring(0, 8) }}...</div>
                    </div>
                  </div>
                </td>
                <td class="px-6 py-4">
                  <div class="text-sm text-slate-300">{{ user.email }}</div>
                  <div class="text-xs text-slate-500">{{ user.phone }}</div>
                </td>
                <td class="px-6 py-4">
                  <span class="px-2 py-1 rounded-full text-xs font-medium" 
                    :class="user.role === 'admin' ? 'bg-purple-500/10 text-purple-400' : 'bg-slate-700 text-slate-300'">
                    {{ user.role }}
                  </span>
                </td>
                <td class="px-6 py-4">
                  <span class="px-2 py-1 rounded-full text-xs font-medium" 
                    :class="user.is_active ? 'bg-emerald-500/10 text-emerald-400' : 'bg-red-500/10 text-red-400'">
                    {{ user.is_active ? 'Actif' : 'Inactif' }}
                  </span>
                </td>
                <td class="px-6 py-4">
                   <span class="px-2 py-1 rounded-full text-xs font-medium" 
                    :class="{
                      'bg-emerald-500/10 text-emerald-400': user.kyc_level >= 2,
                      'bg-amber-500/10 text-amber-400': user.kyc_level === 1,
                      'bg-slate-700 text-slate-300': user.kyc_level === 0
                    }">
                    Niveau {{ user.kyc_level }}
                  </span>
                </td>
                <td class="px-6 py-4 text-xs text-slate-400">
                  {{ formatDate(user.last_login) }}
                </td>
                <td class="px-6 py-4 text-right">
                  <button class="text-indigo-400 hover:text-indigo-300 font-medium text-sm">Détails</button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <!-- Pagination -->
        <div class="px-6 py-4 border-t border-slate-700/50 flex justify-between items-center">
          <button @click="prevPage" :disabled="offset === 0" class="text-slate-400 hover:text-white disabled:opacity-50">
            ← Précédent
          </button>
           <span class="text-slate-500 text-sm">Page {{ currentPage }} / {{ totalPages }}</span>
          <button @click="nextPage" :disabled="offset + limit >= total" class="text-slate-400 hover:text-white disabled:opacity-50">
            Suivant →
          </button>
        </div>
      </div>
    </div>
  </NuxtLayout>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue'
import { useApi } from '@/composables/useApi'

const { adminUserAPI } = useApi()

const loading = ref(true)
const users = ref([])
const total = ref(0)
const limit = ref(20)
const offset = ref(0)

const currentPage = computed(() => Math.floor(offset.value / limit.value) + 1)
const totalPages = computed(() => Math.ceil(total.value / limit.value) || 1)

const fetchUsers = async () => {
  loading.value = true
  try {
    const response = await adminUserAPI.getUsers(limit.value, offset.value)
    users.value = response.data?.users || []
    total.value = response.data?.total || 0
  } catch (error) {
    console.error("Failed to fetch users", error)
  } finally {
    loading.value = false
  }
}

const nextPage = () => {
  if (offset.value + limit.value < total.value) {
    offset.value += limit.value
    fetchUsers()
  }
}

const prevPage = () => {
  if (offset.value >= limit.value) {
    offset.value -= limit.value
    fetchUsers()
  }
}

const formatDate = (dateString) => {
  if (!dateString || dateString.startsWith('0001')) return 'Jamais'
  return new Date(dateString).toLocaleString('fr-FR')
}

onMounted(() => {
  fetchUsers()
})
</script>
