// admin-dashboard/src/app/dashboard/associations/page.tsx
'use client';

import { useState, useEffect } from 'react';
import {
    UserGroupIcon,
    BanknotesIcon,
    MagnifyingGlassIcon,
    EyeIcon,
    NoSymbolIcon,
    CheckCircleIcon,
    ArrowPathIcon,
} from '@heroicons/react/24/outline';
import { getAllAssociations, getAssociationDetails, suspendAssociation, activateAssociation } from '@/lib/api';

interface Association {
    id: string;
    name: string;
    type: string;
    description: string;
    total_members: number;
    treasury_balance: number;
    currency: string;
    status: string;
    created_at: string;
}

export default function AssociationsPage() {
    const [associations, setAssociations] = useState<Association[]>([]);
    const [loading, setLoading] = useState(true);
    const [searchQuery, setSearchQuery] = useState('');
    const [selectedAssociation, setSelectedAssociation] = useState<Association | null>(null);
    const [showDetails, setShowDetails] = useState(false);

    useEffect(() => {
        loadAssociations();
    }, []);

    const loadAssociations = async () => {
        setLoading(true);
        try {
            const response = await getAllAssociations();
            setAssociations(response.data || []);
        } catch (error) {
            console.error('Failed to load associations:', error);
            // Mock data for demo
            setAssociations([
                {
                    id: '1',
                    name: 'Tontine Famille Toure',
                    type: 'tontine',
                    description: 'Tontine mensuelle familiale',
                    total_members: 12,
                    treasury_balance: 1200000,
                    currency: 'XOF',
                    status: 'active',
                    created_at: '2024-01-01',
                },
                {
                    id: '2',
                    name: 'Épargne Commerçants Plateau',
                    type: 'savings',
                    description: 'Caisse de solidarité commerçants',
                    total_members: 45,
                    treasury_balance: 5500000,
                    currency: 'XOF',
                    status: 'active',
                    created_at: '2024-02-15',
                },
                {
                    id: '3',
                    name: 'Crédit Mutuel Artisans',
                    type: 'credit',
                    description: 'Association de crédit pour artisans',
                    total_members: 28,
                    treasury_balance: 3200000,
                    currency: 'XOF',
                    status: 'suspended',
                    created_at: '2024-03-10',
                },
            ]);
        } finally {
            setLoading(false);
        }
    };

    const handleSuspend = async (id: string) => {
        try {
            await suspendAssociation(id);
            loadAssociations();
        } catch (error) {
            console.error('Failed to suspend:', error);
        }
    };

    const handleActivate = async (id: string) => {
        try {
            await activateAssociation(id);
            loadAssociations();
        } catch (error) {
            console.error('Failed to activate:', error);
        }
    };

    const formatCurrency = (amount: number, currency: string) => {
        return new Intl.NumberFormat('fr-FR', { style: 'currency', currency }).format(amount);
    };

    const getTypeLabel = (type: string) => {
        const labels: Record<string, string> = {
            tontine: 'Tontine',
            savings: 'Épargne',
            credit: 'Crédit Mutuel',
            general: 'Général',
        };
        return labels[type] || type;
    };

    const getStatusBadge = (status: string) => {
        const styles: Record<string, string> = {
            active: 'bg-green-100 text-green-800',
            suspended: 'bg-red-100 text-red-800',
            closed: 'bg-gray-100 text-gray-800',
        };
        const labels: Record<string, string> = {
            active: 'Actif',
            suspended: 'Suspendu',
            closed: 'Clôturé',
        };
        return (
            <span className={`px-2 py-1 rounded-full text-xs font-medium ${styles[status] || 'bg-gray-100 text-gray-800'}`}>
                {labels[status] || status}
            </span>
        );
    };

    const filteredAssociations = associations.filter(
        (a) =>
            a.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
            a.type.toLowerCase().includes(searchQuery.toLowerCase())
    );

    const stats = {
        total: associations.length,
        active: associations.filter((a) => a.status === 'active').length,
        totalTreasury: associations.reduce((sum, a) => sum + a.treasury_balance, 0),
        totalMembers: associations.reduce((sum, a) => sum + a.total_members, 0),
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <h1 className="text-2xl font-bold text-gray-900">Gestion des Associations</h1>
                <button
                    onClick={loadAssociations}
                    className="flex items-center space-x-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
                >
                    <ArrowPathIcon className="w-5 h-5" />
                    <span>Actualiser</span>
                </button>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                <div className="bg-white rounded-lg shadow p-4">
                    <div className="flex items-center justify-between">
                        <div>
                            <p className="text-sm text-gray-500">Total Associations</p>
                            <p className="text-2xl font-bold text-gray-900">{stats.total}</p>
                        </div>
                        <UserGroupIcon className="w-10 h-10 text-indigo-500" />
                    </div>
                </div>
                <div className="bg-white rounded-lg shadow p-4">
                    <div className="flex items-center justify-between">
                        <div>
                            <p className="text-sm text-gray-500">Actives</p>
                            <p className="text-2xl font-bold text-green-600">{stats.active}</p>
                        </div>
                        <CheckCircleIcon className="w-10 h-10 text-green-500" />
                    </div>
                </div>
                <div className="bg-white rounded-lg shadow p-4">
                    <div className="flex items-center justify-between">
                        <div>
                            <p className="text-sm text-gray-500">Trésorerie Totale</p>
                            <p className="text-2xl font-bold text-indigo-600">{formatCurrency(stats.totalTreasury, 'XOF')}</p>
                        </div>
                        <BanknotesIcon className="w-10 h-10 text-indigo-500" />
                    </div>
                </div>
                <div className="bg-white rounded-lg shadow p-4">
                    <div className="flex items-center justify-between">
                        <div>
                            <p className="text-sm text-gray-500">Membres Total</p>
                            <p className="text-2xl font-bold text-gray-900">{stats.totalMembers}</p>
                        </div>
                        <UserGroupIcon className="w-10 h-10 text-gray-500" />
                    </div>
                </div>
            </div>

            {/* Search */}
            <div className="bg-white rounded-lg shadow p-4">
                <div className="relative">
                    <MagnifyingGlassIcon className="w-5 h-5 absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                    <input
                        type="text"
                        placeholder="Rechercher une association..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
                    />
                </div>
            </div>

            {/* Table */}
            <div className="bg-white rounded-lg shadow overflow-hidden">
                <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-50">
                        <tr>
                            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Association
                            </th>
                            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Type
                            </th>
                            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Membres
                            </th>
                            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Trésorerie
                            </th>
                            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Statut
                            </th>
                            <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                        {loading ? (
                            <tr>
                                <td colSpan={6} className="px-6 py-12 text-center text-gray-500">
                                    Chargement...
                                </td>
                            </tr>
                        ) : filteredAssociations.length === 0 ? (
                            <tr>
                                <td colSpan={6} className="px-6 py-12 text-center text-gray-500">
                                    Aucune association trouvée
                                </td>
                            </tr>
                        ) : (
                            filteredAssociations.map((association) => (
                                <tr key={association.id} className="hover:bg-gray-50">
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <div>
                                            <div className="text-sm font-medium text-gray-900">{association.name}</div>
                                            <div className="text-sm text-gray-500 truncate max-w-xs">
                                                {association.description}
                                            </div>
                                        </div>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap">
                                        <span className="px-2 py-1 bg-indigo-100 text-indigo-800 rounded-full text-xs font-medium">
                                            {getTypeLabel(association.type)}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                        {association.total_members}
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {formatCurrency(association.treasury_balance, association.currency)}
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap">{getStatusBadge(association.status)}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <button
                                            onClick={() => {
                                                setSelectedAssociation(association);
                                                setShowDetails(true);
                                            }}
                                            className="text-indigo-600 hover:text-indigo-900 mr-3"
                                            title="Voir détails"
                                        >
                                            <EyeIcon className="w-5 h-5" />
                                        </button>
                                        {association.status === 'active' ? (
                                            <button
                                                onClick={() => handleSuspend(association.id)}
                                                className="text-red-600 hover:text-red-900"
                                                title="Suspendre"
                                            >
                                                <NoSymbolIcon className="w-5 h-5" />
                                            </button>
                                        ) : (
                                            <button
                                                onClick={() => handleActivate(association.id)}
                                                className="text-green-600 hover:text-green-900"
                                                title="Réactiver"
                                            >
                                                <CheckCircleIcon className="w-5 h-5" />
                                            </button>
                                        )}
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>

            {/* Details Modal */}
            {showDetails && selectedAssociation && (
                <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
                    <div className="bg-white rounded-xl shadow-xl max-w-2xl w-full mx-4 max-h-[90vh] overflow-y-auto">
                        <div className="p-6 border-b border-gray-200">
                            <div className="flex justify-between items-start">
                                <div>
                                    <h2 className="text-xl font-bold text-gray-900">{selectedAssociation.name}</h2>
                                    <p className="text-gray-500">{getTypeLabel(selectedAssociation.type)}</p>
                                </div>
                                <button
                                    onClick={() => setShowDetails(false)}
                                    className="text-gray-400 hover:text-gray-600"
                                >
                                    ✕
                                </button>
                            </div>
                        </div>
                        <div className="p-6 space-y-4">
                            <div className="grid grid-cols-2 gap-4">
                                <div className="bg-gray-50 p-4 rounded-lg">
                                    <p className="text-sm text-gray-500">Membres</p>
                                    <p className="text-2xl font-bold text-gray-900">{selectedAssociation.total_members}</p>
                                </div>
                                <div className="bg-indigo-50 p-4 rounded-lg">
                                    <p className="text-sm text-indigo-600">Trésorerie</p>
                                    <p className="text-2xl font-bold text-indigo-600">
                                        {formatCurrency(selectedAssociation.treasury_balance, selectedAssociation.currency)}
                                    </p>
                                </div>
                            </div>
                            <div>
                                <p className="text-sm text-gray-500 mb-1">Description</p>
                                <p className="text-gray-900">{selectedAssociation.description || 'Aucune description'}</p>
                            </div>
                            <div>
                                <p className="text-sm text-gray-500 mb-1">Statut</p>
                                {getStatusBadge(selectedAssociation.status)}
                            </div>
                            <div>
                                <p className="text-sm text-gray-500 mb-1">Date de création</p>
                                <p className="text-gray-900">
                                    {new Date(selectedAssociation.created_at).toLocaleDateString('fr-FR')}
                                </p>
                            </div>
                        </div>
                        <div className="p-6 border-t border-gray-200 flex justify-end space-x-3">
                            <button
                                onClick={() => setShowDetails(false)}
                                className="px-4 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50"
                            >
                                Fermer
                            </button>
                            {selectedAssociation.status === 'active' ? (
                                <button
                                    onClick={() => {
                                        handleSuspend(selectedAssociation.id);
                                        setShowDetails(false);
                                    }}
                                    className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700"
                                >
                                    Suspendre
                                </button>
                            ) : (
                                <button
                                    onClick={() => {
                                        handleActivate(selectedAssociation.id);
                                        setShowDetails(false);
                                    }}
                                    className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
                                >
                                    Réactiver
                                </button>
                            )}
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}

// frontend/pages/associations/index.vue
<template>
  <div class="space-y-6">
    <div class="flex justify-between items-center bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-100 dark:border-gray-700">
      <div>
        <h1 class="text-2xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">Mes Associations</h1>
        <p class="text-gray-500 dark:text-gray-400 mt-1">Gérez vos tontines, groupes d'épargne et crédits mutuels</p>
      </div>
      <button @click="navigateTo('/associations/create')" class="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg flex items-center space-x-2 transition-colors">
        <PlusIcon class="w-5 h-5" />
        <span>Créer une association</span>
      </button>
    </div>

    <!-- Quick Stats -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
      <div v-for="stat in stats" :key="stat.name" class="bg-white dark:bg-gray-800 p-4 rounded-lg shadow-sm border border-gray-100 dark:border-gray-700">
        <div class="flex items-center justify-between mb-2">
          <span class="text-gray-500 dark:text-gray-400 text-sm">{{ stat.name }}</span>
          <component :is="stat.icon" class="w-5 h-5 text-indigo-500" />
        </div>
        <div class="text-2xl font-bold text-gray-900 dark:text-white">{{ stat.value }}</div>
        <div class="text-xs text-green-500 mt-1 flex items-center">
          <ArrowTrendingUpIcon class="w-3 h-3 mr-1" />
          {{ stat.change }}
        </div>
      </div>
    </div>

    <!-- Associations List -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <div v-if="loading" v-for="i in 3" :key="i" class="bg-white dark:bg-gray-800 rounded-lg shadow-sm h-64 animate-pulse">
        <div class="h-4 bg-gray-200 dark:bg-gray-700 rounded w-3/4 m-4"></div>
        <div class="h-32 bg-gray-200 dark:bg-gray-700 m-4 rounded"></div>
        <div class="h-8 bg-gray-200 dark:bg-gray-700 m-4 rounded"></div>
      </div>

      <div v-else-if="associations.length === 0" class="col-span-full text-center py-12 bg-white dark:bg-gray-800 rounded-lg border border-dashed border-gray-300 dark:border-gray-600">
        <UserGroupIcon class="w-16 h-16 mx-auto text-gray-400 mb-4" />
        <h3 class="text-lg font-medium text-gray-900 dark:text-white">Aucune association</h3>
        <p class="text-gray-500 dark:text-gray-400 mb-6">Vous n'avez pas encore rejoint d'association.</p>
        <button @click="navigateTo('/associations/create')" class="text-indigo-600 font-medium hover:text-indigo-500">
          Créer ma première association &rarr;
        </button>
      </div>

      <div v-else v-for="association in associations" :key="association.id" 
           @click="navigateTo(`/associations/${association.id}`)"
           class="group bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-100 dark:border-gray-700 hover:shadow-md transition-all cursor-pointer overflow-hidden relative">
        
        <div class="absolute top-0 right-0 p-4">
          <span :class="[
            'px-2 py-1 rounded-full text-xs font-medium',
            getStatusColor(association.status)
          ]">
            {{ getStatusLabel(association.status) }}
          </span>
        </div>

        <div class="p-6">
          <div class="w-12 h-12 rounded-xl bg-indigo-50 dark:bg-indigo-900/30 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
            <component :is="getTypeIcon(association.type)" class="w-6 h-6 text-indigo-600 dark:text-indigo-400" />
          </div>
          
          <h3 class="text-lg font-bold text-gray-900 dark:text-white mb-1 group-hover:text-indigo-600 transition-colors">{{ association.name }}</h3>
          <p class="text-sm text-gray-500 dark:text-gray-400 mb-4 line-clamp-2">{{ association.description }}</p>
          
          <div class="flex items-center justify-between text-sm text-gray-600 dark:text-gray-300 bg-gray-50 dark:bg-gray-750 p-3 rounded-lg">
            <div class="flex items-center">
              <UsersIcon class="w-4 h-4 mr-1 text-gray-400" />
              <span>{{ association.total_members }} membres</span>
            </div>
            <div class="font-bold text-gray-900 dark:text-white">
              {{ formatCurrency(association.treasury_balance, association.currency) }}
            </div>
          </div>
        </div>
        
        <div class="px-6 py-4 border-t border-gray-100 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-800/50 flex justify-between items-center group-hover:bg-indigo-50/30 dark:group-hover:bg-indigo-900/10 transition-colors">
          <span class="text-xs text-gray-500 dark:text-gray-400">{{ getTypeLabel(association.type) }}</span>
          <ArrowRightIcon class="w-4 h-4 text-gray-400 group-hover:text-indigo-600 group-hover:translate-x-1 transition-all" />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { 
  PlusIcon, 
  UserGroupIcon, 
  UsersIcon, 
  BanknotesIcon, 
  ScaleIcon,
  ArrowTrendingUpIcon,
  ArrowRightIcon,
  BriefcaseIcon
} from '@heroicons/vue/24/outline'

const { associationApi } = useApi()

const loading = ref(true)
const associations = ref<any[]>([])
const stats = ref([
  { name: 'Total Épargné', value: '2.5M FCFA', icon: BanknotesIcon, change: '+12%' },
  { name: 'Associations Actives', value: '3', icon: UserGroupIcon, change: '+1' },
  { name: 'Prêts en cours', value: '150K FCFA', icon: ScaleIcon, change: '0%' }, // ScaleIcon instead of CreditCardIcon for loans/balance
  { name: 'Contributions ce mois', value: '50K FCFA', icon: ArrowTrendingUpIcon, change: '+5%' }
])

const getTypeIcon = (type: string) => {
  switch(type) {
    case 'tontine': return ArrowTrendingUpIcon // Cycle/Turn
    case 'savings': return BanknotesIcon
    case 'credit': return ScaleIcon
    default: return UserGroupIcon
  }
}

const getTypeLabel = (type: string) => {
  switch(type) {
    case 'tontine': return 'Tontine Rotative'
    case 'savings': return 'Groupe d\'Épargne'
    case 'credit': return 'Crédit Mutuel'
    default: return 'Association'
  }
}

const getStatusColor = (status: string) => {
  switch(status) {
    case 'active': return 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400'
    case 'suspended': return 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400'
    case 'closed': return 'bg-gray-100 text-gray-700 dark:bg-gray-900/30 dark:text-gray-400'
    default: return 'bg-gray-100 text-gray-700'
  }
}

const getStatusLabel = (status: string) => {
  switch(status) {
    case 'active': return 'Actif'
    case 'suspended': return 'Suspendu'
    case 'closed': return 'Clôturé'
    default: return status
  }
}

const formatCurrency = (amount: number, currency: string) => {
  return new Intl.NumberFormat('fr-FR', { style: 'currency', currency: currency || 'XOF' }).format(amount)
}

onMounted(async () => {
  try {
    const response = await associationApi.getAll()
    associations.value = response.data
  } catch (err) {
    console.error('Failed to load associations', err)
    // Mock data for demo if API fails/not ready
    associations.value = [
      {
        id: '1',
        name: 'Tontine Famille Toure',
        type: 'tontine',
        description: 'Tontine mensuelle pour la famille et les amis proches.',
        total_members: 12,
        treasury_balance: 1200000,
        currency: 'XOF',
        status: 'active'
      },
      {
        id: '2',
        name: 'Épargne Commerçants',
        type: 'savings',
        description: 'Caisse de solidarité pour les commerçants du marché.',
        total_members: 45,
        treasury_balance: 5500000,
        currency: 'XOF',
        status: 'active'
      }
    ]
  } finally {
    loading.value = false
  }
})
</script>
